### PR TITLE
Switch to conda-build 3 syntax + update

### LINKED ISSUE #12: Failed to support multiple versions of numpy
Issue:

This package uses the numpy C-API, and the most recent update to numpy means that it needs to be built separately to support numpy 1.13 and 1.14.  Unfortunately, this package is not dealing with that properly, as seen for example in moble/quaternion#82.  Users with 1.13 are able to conda install this package without upgrading numpy even if it was built on 1.14.

In #10 (now reverted) I tried to improve this recipe to support those versions as separate variants, as described in the documentation [here](https://conda.io/docs/user-guide/tasks/build-packages/variants.html).  Specifically, I added `recipe/conda_build_config.yaml` with

```yaml
numpy:
  - 1.13
  - 1.14
```

and in `meta.yaml` itself, I updated the requirements to include

```yaml
requirements:
  build:
    - numpy {{ numpy }}
   run:
    - numpy {{ numpy }}
```

But after the update completed, trying to install or upgrade the quaternion package leads to a downgrade of numpy to version 1.13.  I verified that I could reproduce this in a fresh environment.  I ran these commands:

```
conda create -y -n quaternion_test python numpy
conda activate quaternion_test
conda install -c conda-forge quaternion
```

The last step gave this output:

```
The following NEW packages will be INSTALLED:

    quaternion:      2018.5.10.13.50.12-py36_1 conda-forge

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0                          --> 2018.4.16-0           conda-forge
    certifi:         2018.4.16-py36_0                      --> 2018.4.16-py36_0      conda-forge
    openssl:         1.0.2o-h26aff7b_0                     --> 1.0.2o-0              conda-forge

The following packages will be DOWNGRADED:

    numpy:           1.14.3-py36h9d02e6b_0                 --> 1.13.3-py36ha9ae307_4    
```

The rerendering for #10 inserted all sorts of extra builds for both 1.13 and 1.14, with those versions in the names of the builds.  Everything appeared to run correctly, so I merged the PR.  But after the update to anaconda, I found that [the conda package files themselves](https://anaconda.org/conda-forge/quaternion/files) did not actually reference the numpy versions in any way (including the absence of the variant hash I was expecting).  I now see that if I had read through the logs of the CI tests, I would have seen that indeed those files were not generated with any variant information — just the python versions.

What have I done wrong?  How can I ensure that the files are actually built and named differently for the different numpy versions?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at <...>anaconda3/envs/quaternion_test:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
intel-openmp              2018.0.0                      8  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
mkl                       2018.0.2                      1  
mkl_fft                   1.0.1            py36h917ab60_0  
mkl_random                1.0.1            py36h78cc56f_0  
ncurses                   6.1                  h0a44026_0  
numpy                     1.14.3           py36h9d02e6b_0  
numpy-base                1.14.3           py36ha9ae307_0  
openssl                   1.0.2o               h26aff7b_0  
pip                       10.0.1                   py36_0  
python                    3.6.5                hc167b69_1  
readline                  7.0                  hc1231fa_4  
setuptools                39.1.0                   py36_0  
sqlite                    3.23.1               hf1716c9_0  
tk                        8.6.7                h35a86e2_3  
wheel                     0.31.0                   py36_0  
xz                        5.2.3                h727817e_4  
zlib                      1.2.11               hf3cbc9b_2  

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : quaternion_test
    active env location : <...>anaconda3/envs/quaternion_test
            shell level : 1
       user config file : <~>/.condarc
 populated config files : <~>/.condarc
          conda version : 4.5.3
    conda-build version : 3.10.2
         python version : 3.6.5.final.0
       base environment : <...>anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : <...>anaconda3/pkgs
                          <~>/.conda/pkgs
       envs directories : <...>anaconda3/envs
                          <~>/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.3 requests/2.18.4 CPython/3.6.5 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by dougalsutherland**
Fixes #12. (I'll also mark the old builds as `broken` after the new ones are up.)

### CODE REVIEW

**Comment by dougalsutherland** [comment]
To double-check, you can see in the logs that conda-build does install `numpy 1.13.3-py36_blas_openblas_201` when building, and at test time it uses `1.14.3-py36_blas_openblas_200`.

This is definitely what you should do for now and will never produce a broken package (unless numpy breaks ABI compatibility in a minor release). But an aside that could be relevant in the future:

Say when python 3.7 comes out, there's no numpy 1.13 package for it (because we've moved on to numpy 1.17 or whatever – I don't know the relative release schedules, that doesn't really matter). It would be nice if we could somehow say "give me the oldest available version of numpy that's at least `1.13`." Right now, it would build with `1.13.0` instead of `1.13.3`, and so let users with `1.13.2` or whatever not *have* to upgrade their numpy; in this hypothetical future situation, it would continue building with numpy 1.13 on python 3.6 but numpy 1.16 or whatever on 3.7. @msarahan, there's no option like that, is there? (Would that be a feature request issue on `conda`, for range specifiers, or is there some reason it'd be `conda-build`?)

**Comment by dougalsutherland** [comment]
Hmm, not sure what's up with the Windows failures, [e.g.](https://ci.appveyor.com/project/conda-forge/quaternion-feedstock/build/1.0.24/job/alek2wtra9o540is#L581)
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - quaternion==2018.5.10.13.50.12=py27hfa6e2cd_3
```

**Comment by moble** [comment]
I don't understand the problems, but I'll at least point out that the error quoted above is only for the 2.7 build.  The 3.5 and 3.6 builds fail for different reasons:

```
LINK : fatal error LNK1117: syntax error in option 'MANIFEST:EMBED,ID=2'
```

and

```
c:\bld\quaternion_1526324747218\_h_env\include\pyport.h(6) : fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
```

respectively.  I don't have the faintest idea how Windows works, but googling suggests that both errors occur due to misconfigurations in the environment.  For example, [this build of some random package](https://ci.appveyor.com/project/LudovicRousseau/pyscard/build/1.0.99) exhibited these same errors until they were fixed in [this commit](https://github.com/LudovicRousseau/pyscard/commit/57d52c0efecb4b0c2592c7d1ac9bca861231e53d?diff=split), which basically changed to just using the default MSVC build environment for python versions >= 3.5.

So maybe
```
  build:
    - {{ compiler('c') }}
```
needs to be augmented by some other option in those cases???
